site_name: EMTECH-Hackathon
site_url: https://github.com/PascaleBorscia/fiware-iot-stack/
repo_url: https://github.com/PascaleBorscia/fiware-iot-stack.git
site_description: IoT Platform EMTECH Hackathon document site
docs_dir: docs/
site_dir: html
markdown_extensions: [toc,tables, fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'quickguide.md'
  - 'APIs':
    - 'Device API': 'device_api.md'
    - 'Lora Agent API': 'loraagent_api.md'
    - 'Data API': 'data_api.md'
    - 'Historic Data API': 'historicdata_api.md'
  - 'Architecture':
    - 'FIWARE Components': 'walkthrough.md'
    - 'Device Backend Gateway (IDAS)': 'device_gateway.md'
    - 'LoRa Agent': 'lora_agent.md'
    - 'Context Broker (Orion)': 'context_broker.md'
    - 'Short Term Historic (STH)': 'sth.md'

