site_name: FIWARE-IOT-Stack
site_url: https://github.com/telefonicaid/fiware-iot-stack/
repo_url: https://github.com/telefonicaid/fiware-iot-stack.git
site_description: IoT Platform document site
docs_dir: docs/
site_dir: html
markdown_extensions: [toc,tables, fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'quickguide.md'
  - 'Walkthrough': 
    - 'Intro': 'walkthrough.md'
    - 'Device Backend Gateway (IDAS)': 'device_gateway.md'
    - 'Context Broker (Orion)': 'context_broker.md'
    - 'Short Term Historic (STH)': 'WorkInProgress.md'
    - 'Connector Framework (Cygnus)': 'WorkInProgress.md'
    - 'Complex Event Processing (Perseo)': 'WorkInProgress.md'
    - 'Identity Management (IDM)': 'WorkInProgress.md'
    - 'Management Portal': 'WorkInProgress.md'
  - 'Reference Manuals': 'WorkInProgress.md'    
    

    
